DROP FUNCTION IF EXISTS sf_current_ms;

DELIMITER //

CREATE FUNCTION sf_current_ms()
    RETURNS BIGINT UNSIGNED
    NOT DETERMINISTIC
    NO SQL
BEGIN
    RETURN CAST(UNIX_TIMESTAMP(SYSDATE(3)) * 1000 AS UNSIGNED);
END//

DELIMITER ;
